name: TeamPlugin
version: '${project.version}'
main: pl.twojanazwa.teamplugin.TeamPlugin
api-version: '1.20'
author: TwojaNazwa
description: Prosty plugin na teamy.
depend: [Vault]
softdepend: [PlaceholderAPI] # PlaceholderAPI nie jest wymagane, ale zalecane

commands:
  team:
    description: Główna komenda do zarządzania teamem.
    usage: /team <stworz|zapros|akceptuj|wyrzuc|usun|lider|degrad|info|pvp|opusc|top|sethome|home>
    aliases: [t]
