name: FirmaPlugin
version: '${project.version}'
main: pl.twojanazwa.firmaplugin.FirmaPlugin
api-version: '1.20'
author: TwojaNazwa
description: Plugin do zarzadzania firmami z systemem skarbca.
depend: [Vault]
softdepend: [PlaceholderAPI]

commands:
  firma:
    description: Glowna komenda do zarzadzania firma.
    usage: /firma <stworz|zapros|akceptuj|wyrzuc|usun|zastepca|degraduj|info|wplac|wyplac|pvp|opusc|top|sethome|home>
    aliases: [f]
